### ISSUE TITLE
[Bug] CSS process 过程存在丢失 cssvar 的问题

### ISSUE THREAD

**Issue by Mmear** [umijs/qiankun#2151]
## What happens?
使用了 css 变量的 css 属性在经过 css process 后丢失了样式信息，排查出来是 css shorthand property 的一种错误情景；

## 复现步骤，错误日志以及相关配置
style 标签中如果存在：
* 一个 css 缩写属性，比如 border、background；
* 该属性使用了 css var;
* 该属性之后还存在着他的子属性；
如下：

```css
.__product_notice__ { 
    z-index: 9999; 
    background: var(--test, blue);
    background-color: red;
}
```
那么这个 stylenode 的 cssText 就会展开该缩写属性并且丢失所有信息：
<img width="1542" alt="image" src="https://user-images.githubusercontent.com/23360556/174062593-ae13bcec-bf1f-4db8-90b1-301721132677.png">

qiankun 此时对他的 selector 进行替换后重新赋值 textContent，就会导致错误的 cssText 被应用到 stylenode 上，导致样式丢失；
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/23360556/174062863-fe0c35dd-e134-42e5-99db-c6d043fa38ac.png">

## 相关环境信息

- **qiankun 版本**  2.7.0
- **浏览器版本**：Google Chrome v100.0.4896.127
- **操作系统**：
