### ISSUE TITLE
[RFC] 关于 qiankun 使用 cypress e2e 的 RFC

### ISSUE THREAD

**Issue by dleged** [umijs/qiankun#2939]
## 背景

> 描述你希望解决的问题的现状，附上相关的 issue 地址

在 qiankun 项目中，我们需要一种可靠的方式来进行端到端（e2e）测试。Cypress 是一个流行的 JavaScript 测试框架，它提供了丰富的功能和易用性，非常适合我们的需求。

## 思路

> 描述大概的解决思路，可以包含 API 设计和伪代码等

1. 安装和配置 Cypress：首先，我们需要在项目中安装 Cypress，并配置它与 qiankun 项目集成。

- 安装 cypress 13.x 的版本
- 配置 cypress.config.js

```
const { defineConfig } = require('cypress');

module.exports = defineConfig({
  projectId: 'xxxxx',
  e2e: {
    setupNodeEvents(on, config) {
    }
  }
});
```
  - scripts 增加 "test:e2e:open": "cypress open --e2e" 、"test:e2e": "node ./scripts/e2e" 两个命令
2. 编写测试用例：使用 Cypress 的命令和断言，我们可以编写针对 qiankun 项目的具体测试用例。这些测试用例可以包括对页面功能、用户交互和 API 调用的测试。

1. 根目录下的 crypess 文件夹编写测试用例相关

3. 持续集成 Github Actions：
  - ci.yml 中新增 cypress 的工作流，以下 jobs 中新增
```
e2e-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.17]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # Set up GitHub Actions caching for Wireit.
      - uses: google/wireit@setup-github-actions-caching/v1
      - name: Install dependency
        run: yarn

      - name: Install examples dependency
        run: yarn examples:install

      - name: Run cypress test
        uses: cypress-io/github-action@v6
        with:
          install: false
          start: yarn examples:start
          wait-on: 'http://localhost:7100,http://localhost:7101,http://localhost:7102,http://localhost:7103,http://localhost:7104,http://localhost:7105,http://localhost:7099'
          wait-on-timeout: 6000
          parallel: true
          record: true
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

  - cypress clude 中创建项目，会有一个projectId 和 录屏密钥。在 cypress.config.js 配置 projectId，ci.yl 中配置环境变量 CYPRESS_RECORD_KEY（在 github - Code security and analysis - Actions - New repository secret 路径下，新增CYPRESS_RECORD_KEY：录屏密钥）
  -  ci 触发 e2e 通过测试的结果如下
![下载](https://github.com/umijs/qiankun/assets/26102884/ec5a20b6-79a4-4f92-be94-170a53fa2492)

  -  [Cypress Cloud](https://cloud.cypress.io/) 记录的录屏结果如下
![22](https://github.com/umijs/qiankun/assets/26102884/9e31e90a-084a-410f-91bc-90c138df2181)

## 跟进

- [ ] 集成 Github Action。
- [ ] 完善端到端的测试用例。
- [ ] PR URL
