### ISSUE TITLE
[Feature Request] 多个应用同时运行在一个页面中时，真正的实现样式隔离了吗？

### ISSUE THREAD

**Issue by masx200** [umijs/qiankun#406]
## Background

多个应用同时运行在一个页面中时，真正的实现样式隔离了吗？

## Proposal

真正的样式隔离应该是要去修改cssrules才行，把每个应用的样式文件中每一条cssrules都添加上前缀才行啊

，也就是说要在浏览器中进行css的抽象语法树转换才行

顺便转换之后把css缓存起来

需要转换的规则有

CSSStyleRule

CSSMediaRule

转换前
```css
div
{
transform:rotate(30deg);
}
```
转换后
```css
#foobar div
{
transform:rotate(30deg);
}
```
