### ISSUE TITLE
[Bug]微应用 CSS 加载方式导致的静态资源路径错误

### ISSUE THREAD

**Issue by jzz4012650** [umijs/qiankun#670]
## What happens?

微应用的主 CSS 文件被 `qiankun` 使用 `fetch()` 加载，并以 `<style>` 标签的形式插入到页面中，如下图：
![image](https://user-images.githubusercontent.com/4429264/84740699-6c232880-afe0-11ea-96ae-bee12f975f6c.png)

这种实现方式将导致 CSS 中所有相对路径 `url('../xx')` 形式引入的静态资源地址错误。（例如 Vue-CLI 构建出来的静态资源都是这种形式）。

一种可能的解决方式是采用 `publicPath`：
https://github.com/umijs/qiankun/issues/217#issuecomment-644550750

那么问题来了，为何是 `<style>` 标签的形式插入 DOM，而不是 `<link>` 的形式？

## 相关环境信息

- **qiankun 版本** 2.0.11
- **浏览器版本**：83.0.4103.97
- **操作系统**：macOS 10.14.6

**Comment by kuitos** [comment]
解决方案你也提到了 [#217 (comment)](https://github.com/umijs/qiankun/issues/217#issuecomment-644550750)

style 方式的目的为了优化加载体验，如果是 link 方式，每次切换到子应用会重新触发 css 的网络请求，且无法确保 html 的渲染会被样式渲染阻塞，即在 css 的网络请求回来之前，子应用的页面可能会出现短暂的「无样式」情况。

**Comment by CareyToboo** [comment]
如果引入的是，第三方的样式文件（非自己项目下的）依赖 “相对资源字体等”文件，怎么处理？ 

是否可以有如下解决方案：

比如，一个子应用 使用了一个已存在的样式文件。 `<link href="https://a.com/b/c.css" />` 
```css

@font-face {
    font-family: myFirstFont;
   /* 把这个 url 先对地址转成全地址 “https://a.com/b/Sansation_Light.ttf” */
    src: url('./Sansation_Light.ttf'), url('./Sansation_Light.eot');  
}

```
