### ISSUE TITLE
[Feature Request] 希望提供可后处理css资源的参数，类似getTemplate参数可处理html模板

### ISSUE THREAD

**Issue by lijing666** [umijs/qiankun#981]
## 背景

很多情况下，为了子应用能够在任意目录部署，我们会将webpack的publicPath设置为相对路径，这样带来的好处就是子应用可以独立部署在任意目录，但是如果这个子应用又想能被集成到qiankun框架中使用时，问题就来了：css样式文件里边的地址都是相对路径，例如 `background-image(url(./images/ok.png))`，无论如何这个`ok.png`都无法请求到，issue里边有很多提出这个问题的同学，如 #808，都建议将webpack的publicPath设置成绝对路径，但是这个对于很多项目来说做不到的，我们通常会发布一个子应用的统一的项目镜像给大家使用，这时候publicPath是确定不了的，所以用相对路径显得就很通用了

## 建议方案
建议提供一个参数如cssProcessor，类似下面，我目前是拿qiankun的源码自己粗糙的加的这个处理器，因为项目紧急可能方案不是很好，期待官方能讨论出更好的方案来吧：
```
start({ 
          prefetch: true ,
          cssProcessor:cssProcessor
   });
```
cssProcessor代码，用来替换一些相对路径，assetPublicPath是内部传递的子应用基础地址
```
function rebuildUrl(cssText,assetPublicPath){
  if(cssText.indexOf('url(../')>-1){
    cssText=cssText.replace(/url\((\.\.\/)+/g,'url('+assetPublicPath);
  }
  if(cssText.indexOf('url("../')>-1){
    cssText=cssText.replace(/url\("(\.\.\/)+/g,'url("'+assetPublicPath);
  }
  if(cssText.indexOf('url(\'../')>-1){
    cssText=cssText.replace(/url\('(\.\.\/)+/g,'url(\''+assetPublicPath);
  }
  return cssText;
}
export var process = function process(appWrapper, stylesheetElement,assetPublicPath) {
  var mountDOM = appWrapper;

  if (!mountDOM) {
    return;
  }

  var tag = (mountDOM.tagName || '').toLowerCase();

  if (tag && stylesheetElement.tagName === 'STYLE') {
    let cssText = stylesheetElement.textContent;
    if(cssText){
      cssText=rebuildUrl(cssText,assetPublicPath);
      stylesheetElement.textContent=cssText;
    }
    var mutator = new MutationObserver(function (mutations) {
      let cssText = stylesheetElement.textContent;
      if(cssText){
        cssText=rebuildUrl(cssText,assetPublicPath);
        stylesheetElement.textContent=cssText;
      }
    });
    mutator.observe(stylesheetElement, {
      childList: true
    });
  }
};
```

## Additional context

欢迎大家来讨论

**Comment by kuitos** [comment]
生产环境 publicPath 使用相对路径不是正确的工程实践，即便是 css 里引用的图片这种场景。

主要原因是 css 里引用的图片不能复用 runtimePublicPath 配置，导致没办法通过 js 及 webpack 动态去处理，而且子应用的 index.html 里的外链 css 会被转换成 style 这种内联样式，所以相对路径就失效了。

其实我们对于这类场景，我们更推荐的方式是：
1. 所以静态资源都上传 cdn，项目里直接引用 cdn 地址（可以webpack插件自动处理&替换）
2. 小的文件（图片、字体等）直接转成 base64 打进 js

我们内部都是这么玩的，所以基本没碰到过这类的问题

**Comment by lijing666** [comment]
> 生产环境 publicPath 使用相对路径不是正确的工程实践，即便是 css 里引用的图片这种场景。
> 
> 主要原因是 css 里引用的图片不能复用 runtimePublicPath 配置，导致没办法通过 js 及 webpack 动态去处理，而且子应用的 index.html 里的外链 css 会被转换成 style 这种内联样式，所以相对路径就失效了。
> 
> 其实我们对于这类场景，我们更推荐的方式是：
> 
> 1. 所以静态资源都上传 cdn，项目里直接引用 cdn 地址（可以webpack插件自动处理&替换）
> 2. 小的文件（图片、字体等）直接转成 base64 打进 js
> 
> 我们内部都是这么玩的，所以基本没碰到过这类的问题

嗯嗯，大厂都是这么玩的，但是我们很多小厂基本没有cdn这种东东，都是在一起部署，所以挺难的，谢谢你了，还是希望官方能给个较好的方案，我现在是改源码也能解决，就是比较粗糙

**Comment by kuitos** [comment]
不传 cdn 转成 base64 打进 js 就行了

**Comment by kuitos** [comment]
getTemplate 拿到的内容里包含已经被转成内联样式的 css 吧？

**Comment by lijing666** [comment]
> 不传 cdn 转成 base64 打进 js 就行了

比较大的字体和图片都是好几M，不太合适base64呢

**Comment by lijing666** [comment]
> getTemplate 拿到的内容里包含已经被转成内联样式的 css 吧？

getTemplate我只是举例子，希望提供额外的参数，类似cssProcessor等，专门可以处理css的

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/faq#%E5%BE%AE%E5%BA%94%E7%94%A8%E6%89%93%E5%8C%85%E4%B9%8B%E5%90%8E-css-%E4%B8%AD%E7%9A%84%E5%AD%97%E4%BD%93%E6%96%87%E4%BB%B6%E5%92%8C%E5%9B%BE%E7%89%87%E5%8A%A0%E8%BD%BD-404

如果你不想写死 `publicPath` ，可以尝试特殊的部署方案：

 1. `nginx` 代理也能解决你这个问题，给资源一个特殊路径，比如说有一张背景图: `./app1/logo.jpg`，主项目服务器收到之后，转发到子项目 app1上。

2. 再比如说你把父子项目部署到一台服务器上，共享路径前缀

3. 再比如说你把子项目的资源都 copy 一份到主项目

**Comment by gongshun** [comment]
> getTemplate 拿到的内容里包含已经被转成内联样式的 css 吧？

不包含，getTemplate 的参数只有 html 字符

**Comment by lijing666** [comment]
> https://qiankun.umijs.org/zh/faq#%E5%BE%AE%E5%BA%94%E7%94%A8%E6%89%93%E5%8C%85%E4%B9%8B%E5%90%8E-css-%E4%B8%AD%E7%9A%84%E5%AD%97%E4%BD%93%E6%96%87%E4%BB%B6%E5%92%8C%E5%9B%BE%E7%89%87%E5%8A%A0%E8%BD%BD-404
> 
> 如果你不想写死 `publicPath` ，可以尝试特殊的部署方案：
> 
> 1. `nginx` 代理也能解决你这个问题，给资源一个特殊路径，比如说有一张背景图: `./app1/logo.jpg`，主项目服务器收到之后，转发到子项目 app1上。
> 2. 再比如说你把父子项目部署到一台服务器上，共享路径前缀
> 3. 再比如说你把子项目的资源都 copy 一份到主项目

嗯嗯，你说的方案都可以解决问题，但是太繁琐，如果可以直接处理css是最方便的，我目前是修改了qiankun的源码，加了cssProcessor给外边处理css可以解决问题，就是要定期合并官方代码，哈哈，比较粗糙。因为这边是希望子项目尽量不用加入太多特殊处理逻辑，如果对部署结构造成改变会带来很多额外的维护问题

**Comment by lijing666** [comment]
> > getTemplate 拿到的内容里包含已经被转成内联样式的 css 吧？
> 
> 不包含，getTemplate 的参数只有 html 字符

对，是原始的html页面字符串

**Comment by fuweichin** [comment]
关于微应用中CSS资源中的相对url最终指向错误，这是qiankun CSS加载器的一个关键bug。qiankun FAQ中提出了一种<a href="https://qiankun.umijs.org/faq#after-the-micro-app-is-bundled-the-font-files-and-images-in-the-css-load-404" target="_blank">变通方法</a>，然而无论是url-loader还是file-loader，都不适用于第三方CDN的CSS。

考虑另一种缓解方法：在样式fetch成功后检查内容中常见的url，如`@import 'xxx.css'`, `url(xxx.jpg)`, `sourceMappingURL=xxx.map`中的路径。将相对url标识变换为绝对URL，以缓解`<link>`变`<style>`带来的相对路径问题。

```js
// require shim/polyfill for Promise, URL, fetch, location.origin
let getAsStyle=(url)=> {
  return fetch(url, {
    method: 'GET',
    headers: {
      'accept': 'text/css,*/*;q=0.1'
    }
  }).then((res)=>{
    if(!res.ok){
      // console.error('GET '+url+' '+res.status+' ('+res.statusText+')');
      throw new Error('Error while loading error '+res.status);
    }
    let contentType=res.headers.get('content-type');
    let type=contentType?contentType.split(/; ?/)[0]:'text/css';
    if(type!=='text/css')
      console.warn('Resource interpreted as Stylesheet but transferred with MIME type '+type+': "'+url+'".');
    return res.text();
  }).then((text)=>{
    let rUrl=/(https?|data):/;
    let replacement=($0, prefix, path, suffix)=>{
      if(rUrl.test(path)){
        return $0;
      }else if(path.charAt(0)==='/' && new URL(url).origin===location.origin){
        return $0;
      }else{
        return prefix+new URL(path, url)+suffix;
      }
    };
    // transform leading `@import 'fineprint.css'`
    text=text.replace(/(@import\s*['"])([^'"]+)(['"])/g, replacement);
    // transform `url(bg.png)`
    text = text.replace(/(url\(\s*['"]?)([^\s()]+)(['"]?\s*\))/g, replacement);
    // transform trailing sourceMappingURL=xxx.map
    text = text.replace(/(\/[*\/][@#] sourceMappingURL=)(\S+)(( \*\/)?[\r\n]*)$/mg, replacement);
    return text;
  }).then((text)=>{
    let style=document.createElement('style');
    style.type='text/css';
    style.setAttribute('data-src', url);
    style.appendChild(document.createTextNode(text));
    return style;
  });
};
```


设有资源`http://127.0.0.1:3010/support/notice.css`
```css
@import 'fineprint.css';
@import url('fineprint.css');
.notice {
  background: #ffffff url(../images/bg.jpg) no-repeat center left;
  background-image: url( '../images/bg.jpg' );
  background-image: url("../images/bg.jpg");
  background-image: url(attr(foo string));
  background-image: url(var(--foo));
}
/*# sourceMappingURL=notice.css.map */
```
通过
```
getAsStyle('http://127.0.0.1:3010/support/notice.css').then((style)=>{
  container.appendChild(style);
});
```
可以得到
```css
@import 'http://127.0.0.1:3010/support/fineprint.css';
@import url('http://127.0.0.1:3010/support/fineprint.css');
.notice {
  background: #ffffff url(http://127.0.0.1:3010/images/bg.jpg) no-repeat center left;
  background-image: url( 'http://127.0.0.1:3010/images/bg.jpg' );
  background-image: url("http://127.0.0.1:3010/images/bg.jpg");
  background-image: url(attr(foo string));
  background-image: url(var(--foo));
}
/*# sourceMappingURL=http://127.0.0.1:3010/support/notice.css.map */
```
